-- AlterTable
ALTER TABLE "TripWallet" ADD COLUMN     "carGoFee" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "driverFee" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "fuelBudget" DOUBLE PRECISION NOT NULL DEFAULT 0;
